# Generated by Django 4.2 on 2024-03-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaultuser.png', null=True, upload_to=''),
        ),
    ]
