# Generated by Django 4.2 on 2023-11-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attrazione',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('luogo', models.CharField(max_length=300)),
                ('via', models.CharField(max_length=500)),
                ('citta', models.CharField(max_length=200)),
                ('costo', models.FloatField()),
                ('tipo', models.CharField(max_length=200)),
                ('oraApertura', models.TimeField(verbose_name='ora apertura')),
                ('oraChiusura', models.TimeField(verbose_name='ora chiusura')),
                ('descrizione', models.TextField()),
                ('attrazione_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Attrazione',
                'verbose_name_plural': 'Attrazioni',
            },
        ),
    ]
