# Generated by Django 4.2 on 2024-02-22 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo della recensione')),
                ('contenuto', models.TextField(max_length=1000, verbose_name='Contenuto della recesione')),
                ('valutazione', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='valutazione della recensione')),
                ('data_creazione', models.DateTimeField(auto_now=True)),
                ('attrazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.attrazione')),
            ],
            options={
                'verbose_name': 'Recensione',
                'verbose_name_plural': 'Recensioni',
            },
        ),
    ]
