# Generated by Django 4.2 on 2023-05-15 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attrazione',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('luogo', models.CharField(max_length=300)),
                ('via', models.CharField(max_length=500)),
                ('citta', models.CharField(max_length=200)),
                ('costo', models.FloatField()),
                ('tipo', models.CharField(max_length=200)),
                ('oraApertura', models.TimeField(verbose_name='ora apertura')),
                ('oraChiusura', models.TimeField(verbose_name='ora chiusura')),
                ('descrizione', models.TextField()),
            ],
            options={
                'verbose_name': 'Attrazione',
                'verbose_name_plural': 'Attrazioni',
            },
        ),
        migrations.CreateModel(
            name='Scelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.DateField()),
                ('oraInizio', models.TimeField(blank=True)),
                ('oraFine', models.TimeField(blank=True)),
                ('durata', models.DurationField()),
                ('attrazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrazione', to='HolidayPlanning.attrazione')),
            ],
            options={
                'verbose_name': 'Scelta',
                'verbose_name_plural': 'Scelte',
            },
        ),
        migrations.CreateModel(
            name='Vacanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataArrivo', models.DateField()),
                ('dataPartenza', models.DateField()),
                ('nrPersone', models.IntegerField()),
                ('budgetDisponibile', models.FloatField()),
                ('scelte', models.ManyToManyField(related_name='vacanze', to='HolidayPlanning.scelta')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Utente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacanza',
                'verbose_name_plural': 'Vacanze',
            },
        ),
    ]
