# Generated by Django 4.1.2 on 2022-10-13 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attrazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('posizione', models.CharField(max_length=300)),
                ('costo', models.FloatField(default=10.5)),
                ('tipo', models.CharField(max_length=200)),
                ('oraInizio', models.DateTimeField(verbose_name='ora inizio')),
                ('oraFine', models.DateTimeField(verbose_name='ora fine')),
            ],
        ),
        migrations.CreateModel(
            name='Giornata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oraSveglia', models.DateTimeField(verbose_name='ora Sveglia')),
                ('oraRientro', models.DateTimeField(verbose_name='Ora Rientro')),
                ('attrazioni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HolidayPlanning.attrazione')),
            ],
        ),
    ]
