# Generated by Django 4.1.2 on 2022-11-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayPlanning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attrazione',
            name='oraApertura',
            field=models.TimeField(verbose_name='ora apertura'),
        ),
        migrations.AlterField(
            model_name='attrazione',
            name='oraChiusura',
            field=models.TimeField(verbose_name='ora chiusura'),
        ),
        migrations.AlterField(
            model_name='scelta',
            name='giorno',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='scelta',
            name='oraFine',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='scelta',
            name='oraInizio',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacanza',
            name='dataArrivo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacanza',
            name='dataPartenza',
            field=models.DateField(),
        ),
    ]
