# Generated by Django 4.2 on 2023-10-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayPlanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrazione',
            name='attrazione_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
