# Generated by Django 4.2 on 2024-03-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayPlanning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spostamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora_partenza', models.TimeField(blank=True)),
                ('ora_arrivo', models.TimeField(blank=True)),
                ('durata_spostamento', models.DurationField()),
                ('veicolo', models.CharField(blank=True, max_length=30)),
                ('tipo_spostamento', models.CharField(max_length=10)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('scelta_arrivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivo', to='HolidayPlanning.scelta')),
                ('scelta_partenza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partenza', to='HolidayPlanning.scelta')),
            ],
            options={
                'verbose_name': 'Spostamento',
                'verbose_name_plural': 'Spostamenti',
            },
        ),
    ]
