# Generated by Django 4.2 on 2024-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayPlanning', '0002_spostamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacanza',
            name='spostamenti',
            field=models.ManyToManyField(related_name='spostamenti', to='HolidayPlanning.spostamento'),
        ),
        migrations.AlterField(
            model_name='spostamento',
            name='durata_spostamento',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
