# Generated by Django 4.2 on 2023-04-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayPlanning', '0002_alter_attrazione_oraapertura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attrazione',
            options={'verbose_name': 'Attrazione', 'verbose_name_plural': 'Attrazioni'},
        ),
        migrations.AlterModelOptions(
            name='giornata',
            options={'verbose_name': 'Giornata', 'verbose_name_plural': 'Giornate'},
        ),
        migrations.AlterModelOptions(
            name='scelta',
            options={'verbose_name': 'Scelta', 'verbose_name_plural': 'Scelte'},
        ),
        migrations.AlterModelOptions(
            name='vacanza',
            options={'verbose_name': 'Vacanza', 'verbose_name_plural': 'Vacanze'},
        ),
        migrations.RemoveField(
            model_name='vacanza',
            name='totGiorni',
        ),
        migrations.RemoveField(
            model_name='vacanza',
            name='totNotti',
        ),
    ]
