# Generated by Django 4.2 on 2024-03-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayPlanning', '0003_vacanza_spostamenti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanza',
            name='budgetDisponibile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
