# Generated by Django 4.2 on 2023-10-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayPlanning', '0003_alter_attrazione_attrazione_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attrazione',
            name='attrazione_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
