# Generated by Django 4.2 on 2024-02-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_recensione'),
        ('HolidayPlanning', '0004_alter_attrazione_attrazione_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scelta',
            name='attrazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrazione', to='attractions.attrazione'),
        ),
        migrations.DeleteModel(
            name='Attrazione',
        ),
    ]
